apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: simpleapp
        image: us-central1-docker.pkg.dev/dev-utility-460312-j5/myregistry/sampleapp:latest
        ports:
        - containerPort: 80
